### ISSUE TITLE
优化对markdown的标题语法支持

### ISSUE THREAD

**Issue by senmer** [chengzhongxue/halo-theme-pix#11]
![image](https://github.com/chengzhongxue/halo-theme-pix/assets/39426147/4d9aebdb-1c53-4253-baf2-c47c41679aca)

**Comment by senmer** [comment]
markdown的一二级...标题，直接显示了源代码

**Comment by chengzhongxue** [comment]
![image](https://github.com/chengzhongxue/halo-theme-pix/assets/89380218/07c644d1-f64c-4812-be94-8a37d7048ced)
你语法不对
![image](https://github.com/chengzhongxue/halo-theme-pix/assets/89380218/baa540e4-e46c-4242-a3d9-3faad0c77c66)
你没空格吧  #号后面

**Comment by senmer** [comment]
![image](https://github.com/chengzhongxue/halo-theme-pix/assets/39426147/2ad244d9-fbb8-4b54-bf14-cd343846274f)
![e6e2606648806b401b429647efe26c6](https://github.com/chengzhongxue/halo-theme-pix/assets/39426147/059399c6-832e-472a-a360-28affc36c696)
