### ISSUE TITLE
MD语法写的表格异常显示

### ISSUE THREAD

**Issue by itscolor** [chengzhongxue/halo-theme-pix#2]
RT. 文本或许是受限于主题宽度，导致文本无法居中对称显示，全部为缩进状态的；另外希望增加表格的框显示，能增加背景色或者材质选择就更好了，与主题背景色区分开来。

显示如图：![Snipaste_2023-11-07_17-19-48](https://easyimage.oneleaf.asia/i/2023/11/08/h0yi6s.webp)

**Comment by chengzhongxue** [comment]
已经解决1.0.1更新
