### ISSUE TITLE
代码框没有标题

### ISSUE THREAD

**Issue by 2949193550** [chengzhongxue/halo-theme-pix#7]
![7454f4c12ee159b26bc6cebdca321ef](https://github.com/chengzhongxue/halo-theme-pix/assets/63438310/17d843f7-1260-4a98-8264-268b0607dbe1)

**Comment by itscolor** [comment]
附议问题反馈：
  - 安装必要工具
   ```Docker
  apt install wget curl sudo vim git  -y
   ```

此pix主题，我MD语法写的代码块，红绿灯会显示在文本中，错行了。是因为我输入了Docker的文本类型，实际我是想让Docker文字出现在红绿灯右侧的。此MD写作方式，其余主题是不会异常的，包括Halo官方主题也是正常显示的，红绿灯右侧会正常出现Docker文字。
